export const AGENT_WALLET_ABI = [
  {
    name: 'execute',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'target', type: 'address' },
      { name: 'value', type: 'uint256' },
      { name: 'data', type: 'bytes' },
    ],
    outputs: [{ type: 'bytes' }],
  },
  {
    name: 'withdraw',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'to', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [],
  },
  { name: 'pause', type: 'function', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  { name: 'unpause', type: 'function', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  {
    name: 'queueCall',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'target', type: 'address' },
      { name: 'selector', type: 'bytes4' },
      { name: 'checkRecipient', type: 'bool' },
      { name: 'checkAmount', type: 'bool' },
      { name: 'maxAmount', type: 'uint256' },
    ],
    outputs: [],
  },
  { name: 'applyCall', type: 'function', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  {
    name: 'cancelCallQueue',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    name: 'removeCall',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'target', type: 'address' },
      { name: 'selector', type: 'bytes4' },
    ],
    outputs: [],
  },
  {
    name: 'addRecipient',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'target', type: 'address' },
      { name: 'sel', type: 'bytes4' },
      { name: 'recipient', type: 'address' },
    ],
    outputs: [],
  },
  {
    name: 'removeRecipient',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'target', type: 'address' },
      { name: 'sel', type: 'bytes4' },
      { name: 'recipient', type: 'address' },
    ],
    outputs: [],
  },
  {
    name: 'isRecipientAllowed',
    type: 'function',
    stateMutability: 'view',
    inputs: [
      { name: 'target', type: 'address' },
      { name: 'sel', type: 'bytes4' },
      { name: 'recipient', type: 'address' },
    ],
    outputs: [{ type: 'bool' }],
  },
  {
    name: 'setTokenPolicy',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'token', type: 'address' },
      { name: '_dailyLimit', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    name: 'revokeTokenPolicy',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'token', type: 'address' }],
    outputs: [],
  },
  {
    name: 'queueLimitChange',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: '_txLimit', type: 'uint256' },
      { name: '_dailyLimit', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    name: 'applyLimitChange',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    name: 'cancelLimitChange',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    name: 'decreaseLimits',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: '_txLimit', type: 'uint256' },
      { name: '_dailyLimit', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    name: 'transferAgent',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'newAgent', type: 'address' }],
    outputs: [],
  },
  { name: 'acceptAgent', type: 'function', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  {
    name: 'transferGuardian',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'newGuardian', type: 'address' }],
    outputs: [],
  },
  {
    name: 'acceptGuardian',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    name: 'tokenPolicy',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'address' }],
    outputs: [
      { name: 'dailyLimit', type: 'uint256' },
      { name: 'dailySpent', type: 'uint256' },
      { name: 'lastReset', type: 'uint256' },
      { name: 'enabled', type: 'bool' },
    ],
  },
  {
    name: 'pendingCall',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [
      { name: 'target', type: 'address' },
      { name: 'selector', type: 'bytes4' },
      { name: 'checkRecipient', type: 'bool' },
      { name: 'checkAmount', type: 'bool' },
      { name: 'maxAmount', type: 'uint256' },
      { name: 'unlockTime', type: 'uint256' },
      { name: 'queued', type: 'bool' },
    ],
  },
  {
    name: 'pendingLimitChange',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [
      { name: 'txLimit', type: 'uint256' },
      { name: 'dailyLimit', type: 'uint256' },
      { name: 'unlockTime', type: 'uint256' },
      { name: 'queued', type: 'bool' },
    ],
  },
  {
    name: 'ethTxLimit',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    name: 'ethDailyLimit',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    name: 'ethDailySpent',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    name: 'ethLastReset',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    name: 'paused',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'bool' }],
  },
  {
    name: 'agent',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'address' }],
  },
  {
    name: 'guardian',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'address' }],
  },
  {
    name: 'pendingAgent',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'address' }],
  },
  {
    name: 'pendingGuardian',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'address' }],
  },

  {
    name: 'Executed',
    type: 'event',
    inputs: [
      { indexed: true, name: 'target', type: 'address' },
      { indexed: false, name: 'value', type: 'uint256' },
      { indexed: false, name: 'selector', type: 'bytes4' },
    ],
  },
  {
    name: 'Withdrawn',
    type: 'event',
    inputs: [
      { indexed: true, name: 'to', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
    ],
  },
  { name: 'Paused', type: 'event', inputs: [{ indexed: true, name: 'by', type: 'address' }] },
  { name: 'Unpaused', type: 'event', inputs: [{ indexed: true, name: 'by', type: 'address' }] },
  {
    name: 'AgentTransferStarted',
    type: 'event',
    inputs: [{ indexed: true, name: 'newAgent', type: 'address' }],
  },
  {
    name: 'AgentTransferred',
    type: 'event',
    inputs: [
      { indexed: true, name: 'previousAgent', type: 'address' },
      { indexed: true, name: 'newAgent', type: 'address' },
    ],
  },
  {
    name: 'GuardianTransferred',
    type: 'event',
    inputs: [
      { indexed: true, name: 'previousGuardian', type: 'address' },
      { indexed: true, name: 'newGuardian', type: 'address' },
    ],
  },
  {
    name: 'CallQueued',
    type: 'event',
    inputs: [
      { indexed: true, name: 'target', type: 'address' },
      { indexed: false, name: 'selector', type: 'bytes4' },
      { indexed: false, name: 'unlockTime', type: 'uint256' },
    ],
  },
  {
    name: 'CallApplied',
    type: 'event',
    inputs: [
      { indexed: true, name: 'target', type: 'address' },
      { indexed: false, name: 'selector', type: 'bytes4' },
    ],
  },
  {
    name: 'CallQueueCancelled',
    type: 'event',
    inputs: [
      { indexed: true, name: 'target', type: 'address' },
      { indexed: false, name: 'selector', type: 'bytes4' },
    ],
  },
  {
    name: 'CallRemoved',
    type: 'event',
    inputs: [
      { indexed: true, name: 'target', type: 'address' },
      { indexed: false, name: 'selector', type: 'bytes4' },
    ],
  },
  {
    name: 'RecipientAdded',
    type: 'event',
    inputs: [
      { indexed: true, name: 'target', type: 'address' },
      { indexed: true, name: 'selector', type: 'bytes4' },
      { indexed: true, name: 'recipient', type: 'address' },
    ],
  },
  {
    name: 'RecipientRemoved',
    type: 'event',
    inputs: [
      { indexed: true, name: 'target', type: 'address' },
      { indexed: true, name: 'selector', type: 'bytes4' },
      { indexed: true, name: 'recipient', type: 'address' },
    ],
  },
  {
    name: 'LimitChangeQueued',
    type: 'event',
    inputs: [
      { indexed: false, name: 'txLimit', type: 'uint256' },
      { indexed: false, name: 'daily', type: 'uint256' },
      { indexed: false, name: 'unlockTime', type: 'uint256' },
    ],
  },
  {
    name: 'LimitChangeApplied',
    type: 'event',
    inputs: [
      { indexed: false, name: 'txLimit', type: 'uint256' },
      { indexed: false, name: 'daily', type: 'uint256' },
    ],
  },
  { name: 'LimitChangeCancelled', type: 'event', inputs: [] },
  {
    name: 'LimitsDecreased',
    type: 'event',
    inputs: [
      { indexed: false, name: 'txLimit', type: 'uint256' },
      { indexed: false, name: 'daily', type: 'uint256' },
    ],
  },
  {
    name: 'TokenPolicySet',
    type: 'event',
    inputs: [
      { indexed: true, name: 'token', type: 'address' },
      { indexed: false, name: 'dailyLimit', type: 'uint256' },
    ],
  },
  {
    name: 'TokenPolicyRevoked',
    type: 'event',
    inputs: [{ indexed: true, name: 'token', type: 'address' }],
  },
] as const;
